language: node_js
node_js:
  - "7"
  - "node"
  
before_script:
  - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
  - tar xvf ffmpeg-release-amd64-static.tar.xz
  - mv ffmpeg-*.*.*-amd64-static ffmpeg
  - export PATH=$PATH:$PWD/ffmpeg